### ISSUE TITLE
Problemas con imagenes de blogs

### ISSUE THREAD

**Issue by andresderas** [spocasangre/proyecto_aca_2023#27]
El blog esta presentando problemas con las imagenes, no las muestra y en ciertas ocasiones no deja crear el blog.

**Comment by SebastianMagg** [comment]
Cuando el blog esta creado, no muestra la imagen adjunta a ese blog

**Comment by SebastianMagg** [comment]
Ya muestra correctamente la imagen, buen trabajo!
